### ISSUE TITLE
Oxide?

### ISSUE THREAD

**Issue by stephen-cernota** [TorchSE/Torch#5]
Would you guys be open to using Oxide or working with https://github.com/lukespragg ? or is the aim/goal of Torch different than just a plugin system?

I used to run a top Space Engineers server and loved Extender and Essentials,
I recently have been running a Rust server and have really enjoyed Oxide (there were at least 2-3 other Rust plugin systems that died out or are barely crawling along)

---------

Oxide
http://docs.oxidemod.org/

Rust Oxide API
http://docs.oxidemod.org/rust/#getting-started

Rust Oxide Plugins
http://oxidemod.org/plugins/categories/rust.24/?order=rating_weighted

--------

I believe Oxide somewhat support Space Engineers

https://github.com/OxideMod/Oxide/tree/master/Games/Other/Oxide.Game.SpaceEngineers

http://oxidemod.org/threads/oxide-for-space-engineers.17808/

**Comment by Jimmacle** [comment]
This project's scope is beyond server-side modding, the server-side plugin system is only one of Torch's features. The plugin system needs to stay roughly compatible with SESE's system as well. If there's something specific that Oxide offers I'll take a closer look but right now I don't think it's necessary.
